name: Install Linux

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci-install.yml
    with:
      os: ubuntu-latest
      label: Linux
    secrets: inherit
