name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run test suite
        run: bash test.sh
